### PR TITLE
Added twig 3 to requires

### PR DESCRIPTION
**Pull request by creonit-dev**

### CODE REVIEW

**Comment by klaux** [comment]
Please, release it.

**Comment by tifed** [comment]
Come on guys, we need it

**Comment by RevisionTen** [comment]
@Gregwar please consider merging this. Its badly needed.

**Comment by Gregwar** [comment]
Hello,
I am sorry for the huge delay in processing this
Thanks for contributing

**Comment by Gregwar** [comment]
Tagged `v3.0.1`

**Pull request merged**
