### PR TITLE
Fix deprecated Twig_Function_Method usage

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Gregwar** [comment]
Does it breaks some BC?

**Comment by Soullivaneuh** [comment]
@Gregwar Absolutly not. User just has to get twig >= 1.12 that still is a 1.x version.

Code runtime will still be the same. :+1:

**Comment by Gregwar** [comment]
Ok, thanks for contributing

**Comment by Soullivaneuh** [comment]
Thanks. Could we have a new release tag for this?

**Comment by Gregwar** [comment]
Of course
I am away right now, do not hesitate to ping me later if I forget

**Comment by Gregwar** [comment]
tagged `v2.1.0`

**Comment by Soullivaneuh** [comment]
@Gregwar Ok!

BTW, if you need help to maintain Image and ImageBundle project, I would be glad to be part of contributors. ;-)

**Comment by Soullivaneuh** [comment]
`2.1.0`? I would tag a new patch instead because it's not a new feature but a deprecated fix.

What do you think?

**Comment by Gregwar** [comment]
You're right, I tagged `v2.0.21` instead

**Comment by Gregwar** [comment]
I can indeed consider including you as a contributor  ;-)

**Comment by Soullivaneuh** [comment]
> I can indeed consider including you as a contributor ;-)

Thank you. I can help maintaining especially for Image and ImageBundle, but I can help for another if you want me for that. :+1:

**Comment by Gregwar** [comment]
Btw, je suis aussi français :-)

**Comment by Soullivaneuh** [comment]
Ha ha bonjour !

Nice to know it, but I would still speak english on GitHub issues. ;-)

**Comment by Gregwar** [comment]
You are now collaborator of both repositories

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Pull request merged**
