### PR TITLE
StyleCI

### PR DESCRIPTION
**Pull request by Soullivaneuh**
@Gregwar wee need:

* StyleCI setup (https://github.com/Gregwar/Image/pull/90)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Oh... no test on this bundle. Forgot Travis so, I'll removed it. Just StyleCI is needed.

**Comment by Soullivaneuh** [comment]
PR rebased. ping @Gregwar for StyleCI setup.

**Comment by Gregwar** [comment]
StyleCI enabled
BTW, `Gregwar/Image` is marked as failed

**Comment by Soullivaneuh** [comment]
> BTW, `Gregwar/Image` is marked as failed

Probably due to new fixers.

**Comment by Gregwar** [comment]
StyleCI error status for this:

    The provided fixer 'psr0' cannot be disabled unless it was already enabled by your preset.

**Comment by Soullivaneuh** [comment]
Oh ok I see. Will correct it.

BTW, would be great to have styleCI badge on both Image and ImageBundle.

**Pull request merged**
